name       : advancecomp
version    : '2.3'
release    : 5
source     :
    - https://github.com/amadvance/advancecomp/archive/refs/tags/v2.3.tar.gz : 8cb9e36d54bc44d7a1cdaf857a8e646dc407363dd127ef79190693f1a123cf18
homepage   : http://www.advancemame.it/
license    : GPL-3.0-or-later
component  : system.utils
summary    : AdvanceCOMP contains recompression utilities
description: |
    AdvanceCOMP contains recompression utilities for your .zip archives, .png images, .mng video clips and .gz files.
builddeps  :
    - pkgconfig(valgrind)
    - libboost
setup      : |
    autoheader
    %autogen
build      : |
    %make
install    : |
    %make_install
