name       : advancecomp
version    : 1.22
release    : 1
source     :
    - https://github.com/amadvance/advancecomp/archive/v1.22.tar.gz : b8c482027a5f78d9a7f871cbba19cc896ed61653d1d93034c9dbe55484952605
license    : GPL-3.0
component  : system.utils
summary    : AdvanceCOMP contains recompression utilities
description: |
    AdvanceCOMP contains recompression utilities for your .zip archives, .png images, .mng video clips and .gz files.

    It runs in Linux, Mac OS X, DOS, Windows and in all the other Unix like platforms.
builddeps  :
    - pkgconfig(valgrind)
    - libboost
setup      : |
    autoheader
    %autogen
build      : |
    %make
install    : |
    %make_install
