name       : advancecomp
version    : '2.5'
release    : 7
source     :
    - https://github.com/amadvance/advancecomp/archive/refs/tags/v2.5.tar.gz : b6b4333453f028565896dd3547bc930f062df82832d7992cc130ca951c2890a1
homepage   : http://www.advancemame.it/
license    : GPL-3.0-or-later
component  : system.utils
summary    : AdvanceCOMP contains recompression utilities
description: |
    AdvanceCOMP contains recompression utilities for your .zip archives, .png images, .mng video clips and .gz files.
builddeps  :
    - pkgconfig(valgrind)
    - libboost
setup      : |
    autoheader
    %autogen
build      : |
    %make
install    : |
    %make_install
