name       : advancecomp
version    : '2.1'
release    : 3
source     :
    - https://github.com/amadvance/advancecomp/archive/v2.1.tar.gz : 6113c2b6272334af710ba486e8312faa3cee5bd6dc8ca422d00437725e2b602a
license    : GPL-3.0
component  : system.utils
summary    : AdvanceCOMP contains recompression utilities
description: |
    AdvanceCOMP contains recompression utilities for your .zip archives, .png images, .mng video clips and .gz files.

    It runs in Linux, Mac OS X, DOS, Windows and in all the other Unix like platforms.
builddeps  :
    - pkgconfig(valgrind)
    - libboost
setup      : |
    autoheader
    %autogen
build      : |
    %make
install    : |
    %make_install
