name       : advancecomp
version    : 1.23
release    : 2
source     :
    - https://github.com/amadvance/advancecomp/archive/v1.23.tar.gz : fe89d6ab382efc6b6be536b8d58113f36b83d82783d5215c261c14374cba800a
license    : GPL-3.0
component  : system.utils
summary    : AdvanceCOMP contains recompression utilities
description: |
    AdvanceCOMP contains recompression utilities for your .zip archives, .png images, .mng video clips and .gz files.

    It runs in Linux, Mac OS X, DOS, Windows and in all the other Unix like platforms.
builddeps  :
    - pkgconfig(valgrind)
    - libboost
setup      : |
    autoheader
    %autogen
build      : |
    %make
install    : |
    %make_install
